# Generated by Django 5.0.2 on 2024-04-18 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='work',
            field=models.CharField(choices=[('P', 'Product'), ('S', 'Service')], default='P', max_length=20),
        ),
    ]
