# Generated by Django 5.0.2 on 2024-04-20 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='address_type',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='kilometer',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='street_name',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
