# Generated by Django 5.0.2 on 2024-04-20 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_address_address_type_userprofile_kilometer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='billing_address',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='delivery_address',
        ),
    ]
