# Generated by Django 5.0.2 on 2024-04-22 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_userprofile_address_line_userprofile_alter_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='alter_number',
            field=models.IntegerField(default=0, max_length=15),
        ),
        migrations.AddField(
            model_name='address',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
    ]
