# Generated by Django 5.0.2 on 2024-04-22 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_address_alter_number_address_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='alter_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='alter_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone_number',
            field=models.IntegerField(default=0),
        ),
    ]
