# Generated by Django 5.0.2 on 2024-04-23 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_address_alter_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='bussiness_credit',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='credit_day',
            field=models.BooleanField(default=True),
        ),
    ]
