# Generated by Django 5.0.2 on 2024-04-23 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_userprofile_bussiness_credit_userprofile_credit_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='bussiness_credit',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='credit_day',
            field=models.IntegerField(default=0),
        ),
    ]
