# Generated by Django 5.0.6 on 2024-05-25 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_userprofile_bussiness_credit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='credit_day1',
            field=models.IntegerField(default=0),
        ),
    ]
