# Generated by Django 5.0.2 on 2024-04-20 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='zipcode',
            field=models.TextField(default=''),
        ),
    ]
