# Generated by Django 5.0.2 on 2024-04-20 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_category_zipcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='zipcode',
        ),
    ]
